export const ORANGE_HRM_LOGIN_READY_TIMEOUT = 15_000;
export const ORANGE_HRM_POST_SUBMIT_TIMEOUT = 15_000;
export const ORANGE_HRM_ADMIN_SEARCH_TIMEOUT = 15_000;
export const ORANGE_HRM_LOADING_OVERLAY_APPEAR_TIMEOUT = 2_000;
